/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LocationSegments } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface BreadcrumbNav {
        "location": LocationSegments;
    }
    interface BreadcrumbNavItem {
        "link": string;
    }
    interface MainNavigation {
    }
    interface TextSection {
    }
    interface WorkList {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBreadcrumbNavElement extends Components.BreadcrumbNav, HTMLStencilElement {
    }
    var HTMLBreadcrumbNavElement: {
        prototype: HTMLBreadcrumbNavElement;
        new (): HTMLBreadcrumbNavElement;
    };
    interface HTMLBreadcrumbNavItemElement extends Components.BreadcrumbNavItem, HTMLStencilElement {
    }
    var HTMLBreadcrumbNavItemElement: {
        prototype: HTMLBreadcrumbNavItemElement;
        new (): HTMLBreadcrumbNavItemElement;
    };
    interface HTMLMainNavigationElement extends Components.MainNavigation, HTMLStencilElement {
    }
    var HTMLMainNavigationElement: {
        prototype: HTMLMainNavigationElement;
        new (): HTMLMainNavigationElement;
    };
    interface HTMLTextSectionElement extends Components.TextSection, HTMLStencilElement {
    }
    var HTMLTextSectionElement: {
        prototype: HTMLTextSectionElement;
        new (): HTMLTextSectionElement;
    };
    interface HTMLWorkListElement extends Components.WorkList, HTMLStencilElement {
    }
    var HTMLWorkListElement: {
        prototype: HTMLWorkListElement;
        new (): HTMLWorkListElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "breadcrumb-nav": HTMLBreadcrumbNavElement;
        "breadcrumb-nav-item": HTMLBreadcrumbNavItemElement;
        "main-navigation": HTMLMainNavigationElement;
        "text-section": HTMLTextSectionElement;
        "work-list": HTMLWorkListElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface BreadcrumbNav {
        "location"?: LocationSegments;
    }
    interface BreadcrumbNavItem {
        "link"?: string;
    }
    interface MainNavigation {
    }
    interface TextSection {
    }
    interface WorkList {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "breadcrumb-nav": BreadcrumbNav;
        "breadcrumb-nav-item": BreadcrumbNavItem;
        "main-navigation": MainNavigation;
        "text-section": TextSection;
        "work-list": WorkList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "breadcrumb-nav": LocalJSX.BreadcrumbNav & JSXBase.HTMLAttributes<HTMLBreadcrumbNavElement>;
            "breadcrumb-nav-item": LocalJSX.BreadcrumbNavItem & JSXBase.HTMLAttributes<HTMLBreadcrumbNavItemElement>;
            "main-navigation": LocalJSX.MainNavigation & JSXBase.HTMLAttributes<HTMLMainNavigationElement>;
            "text-section": LocalJSX.TextSection & JSXBase.HTMLAttributes<HTMLTextSectionElement>;
            "work-list": LocalJSX.WorkList & JSXBase.HTMLAttributes<HTMLWorkListElement>;
        }
    }
}
